name: release

on:
  push:
    branches: ['main']

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v2
        with:
          go-version: 1.19
          cache: true

      - uses: ko-build/setup-ko@v0.6

      - run: ko build --bare --sbom none .
